### ISSUE TITLE
DSL temperature

### ISSUE THREAD

**Issue by miziha-zp** [starmemda/CAMoE#1]
thanks for your great work, it looks very strong baseline to explore.  a simple Question about DSL, in your expriment,whta's  the temperature ? I can't find anything in your paper....

**Comment by starmemda** [comment]
We are updating our paper, in which we stated the temperature.

**Comment by miziha-zp** [comment]
> We are updating our paper, in which we stated the temperature.

waiting for your new paper to reproduce.

**Comment by huangyuhui666** [comment]
sorry to bother you, but I still haven't found the temperature in the paper

**Comment by huangyuhui666** [comment]
> We are updating our paper, in which we stated the temperature.


sorry to bother you, but I still haven't found the temperature in the paper
