### ISSUE TITLE
Contradiction between code and formula

### ISSUE THREAD

**Issue by char-Fyzhao** [starmemda/CAMoE#5]
hi，I have read your paper, but I have some questions.
![image](https://user-images.githubusercontent.com/71687094/142354765-1fd1d9ba-e885-4847-8ea3-e81c53fefddf.png)
According to the code you left, I found that your formula is inconsistent with the code.
![image](https://user-images.githubusercontent.com/71687094/142355622-5c48d669-be63-475c-85a8-55982b0ed031.png)
Which one should I choose?

**Comment by starmemda** [comment]
Sorry for forgetting to submit the newest version. And we have updated it.
